import type { FastifyInstance } from "fastify";
import authRoutes          from "./auth.js";
import userRoutes          from "./users.js";
import settingsRoutes      from "./settings.js";
import accountRoutes       from "./accounts.js";
import contactRoutes       from "./contacts.js";
import contactImportRoutes from "./contacts-import.js";
import pipelineRoutes      from "./pipelines.js";
import noteRoutes          from "./notes.js";
import searchRoutes        from "./search.js";
import messagingRoutes     from "../modules/messaging/messaging.routes.js";
import campaignRoutes      from "../modules/messaging/campaign.routes.js";
import chatbotRoutes       from "../modules/messaging/chatbot.routes.js";
import widgetRoutes        from "../modules/messaging/widget.routes.js";
import workflowRoutes      from "../modules/automation/workflow.routes.js";
import calendarRoutes      from "../modules/calendar/calendar.routes.js";
import formRoutes          from "../modules/forms/form.routes.js";
import funnelRoutes        from "../modules/funnels/funnel.routes.js";
import reputationRoutes    from "../modules/reputation/reputation.routes.js";
import paymentRoutes       from "../modules/payments/payment.routes.js";

export async function registerRoutes(app: FastifyInstance) {
  app.register(authRoutes,          { prefix: "/v1/auth" });
  app.register(userRoutes,          { prefix: "/v1/users" });
  app.register(settingsRoutes,      { prefix: "/v1/settings" });
  app.register(accountRoutes,       { prefix: "/v1/accounts" });
  app.register(contactRoutes,       { prefix: "/v1/contacts" });
  app.register(contactImportRoutes, { prefix: "/v1/contacts" });
  app.register(pipelineRoutes,      { prefix: "/v1/pipelines" });
  app.register(noteRoutes,          { prefix: "/v1/notes" });
  app.register(searchRoutes,        { prefix: "/v1/search" });
  app.register(messagingRoutes,     { prefix: "/v1/messaging" });
  app.register(campaignRoutes,      { prefix: "/v1/campaigns" });
  app.register(chatbotRoutes,       { prefix: "/v1/chatbot" });
  app.register(widgetRoutes,        { prefix: "/v1/messaging/widget" });
  app.register(workflowRoutes,      { prefix: "/v1/workflows" });
  app.register(calendarRoutes,      { prefix: "/v1/calendar" });
  app.register(formRoutes,          { prefix: "/v1/forms" });
  app.register(funnelRoutes,        { prefix: "/v1/funnels" });
  app.register(reputationRoutes,    { prefix: "/v1/reputation" });
  app.register(paymentRoutes,       { prefix: "/v1/payments" });
}
